### ISSUE TITLE
Metric "environmental-power-status" is invalid

### ISSUE THREAD

**Issue by amber-zhang** [zhmcclient/zhmc-prometheus-exporter#152]
zhmc-expoter returns error.
![error](https://user-images.githubusercontent.com/6112761/122033435-1a83c880-ce03-11eb-8bc4-30fb02263403.png)

Suspect the error is related with zhmc version. we use the sample metric.yaml .

**Comment by andy-maier** [comment]
The HMC API book for z15 still documents that metrics group unchanged.
Which version of zhmc-prometheus-exporter are you using?

**Comment by andy-maier** [comment]
A quick fix is to disable this metric group in the metrics.yml file around line 138:

```
  environmental-power-status:
    prefix: cpc
    fetch: false     # <-- to disable it
    if: "hmc_version>='2.15.0'"
    labels:
      - name: cpc
        value: resource
```
