### ISSUE TITLE
Classic metrics missing from example

### ISSUE THREAD

**Issue by bluecmd** [zhmcclient/zhmc-prometheus-exporter#28]
Hi, I'm running without DPM. I want to use e.g. `cpc-usage-overview` but using the example metrics.yaml results in:

```
In /etc/zhmc-prometheus-exporter/metrics.yaml, you specified partition-usage as a metric group, but you did not specify it within the metric_groups section.
```

My metrics.yaml is:
```
metric_groups:
  # These will only find something if you are in classic mode
  cpc-usage-overview:
    prefix: cpc
    fetch: True
  logical-partition-usage:
    prefix: lpar 
    fetch: True
  channel-usage:
    prefix: channel 
    fetch: True
```

Having examples for these 3 would be useful.
