### ISSUE TITLE
Cannot handle string metrics

### ISSUE THREAD

**Issue by bluecmd** [zhmcclient/zhmc-prometheus-exporter#31]
Hi,

I'm trying to use this exporter to monitor channel usage. In my HMC (2.14.1) this is exported under:
```
metric_groups:
  channel-usage:
    prefix: channel
    fetch: True

metrics:
  channel-usage:
    channel-name:
      percent: False
      exporter_name: name
      exporter_desc: The name of the channel in the form CSS.Chpid
    shared-channel:
      percent: False
      exporter_name: is_shared
      exporter_desc: True if the channel is shared among logical partitions, and false if it is not
    logical-partition-name:
      percent: False
      exporter_name: lpar_name
      exporter_desc: For channel types for which logical partition names are available, the name of the owning logical partition or the value "shared" if the channel is shared. For other channel types for which the name is not available (for example, coupling channels), the value is always an empty string.
    channel-usage:
      percent: True
      exporter_name: usage
      exporter_desc: The channel percent usage
```

However, this fails to scrape:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/exposition.py", line 52, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/exposition.py", line 40, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/exposition.py", line 137, in generate_latest
    output.append(sample_line(s))
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/exposition.py", line 103, in sample_line
    line.name, labelstr, floatToGoString(line.value), timestamp)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/utils.py", line 9, in floatToGoString
    d = float(d)
ValueError: ("could not convert string to float: '0.0D'", Metric(zhmc_channel_name, The name of the channel in the form CSS.Chpid, gauge, , [Sample(name='zhmc_channel_name', labels={'resource': 'xxxx'}, value='0.0D', timestamp=None, exemplar=None)]))
```

Leaving the metrics undefined in the configuration still results in the error above, but with a generated metric name:

```
[..]
ValueError: ("could not convert string to float: '0.0D'", Metric(zhmc_channel_channel_name, channel name, gauge, , [Sample(name='zhmc_channel_channel_name', labels={'resource': 'xxxx'}, value='0.0D', timestamp=None, exemplar=None)]))
```

**Request:** It would be useful to be able to specify e.g. `text: True` which would then produce unit metrics like e.g. `zhmc_channel_name{value="0.0D"} 1`.

**Comment by andy-maier** [comment]
Hi Christian.
While I can understand your idea, it does not seem to be possible to have metric values of string type in Prometheus. See this issue: https://github.com/prometheus/prometheus/issues/2227

We will need to find another solution, e.g. by representing these strings as labels.

**Comment by bluecmd** [comment]
> We will need to find another solution, e.g. by representing these strings as labels.

Exactly, that was what I was trying to explain in my example in the final line.

Thanks for your consideration! :-)

**Comment by andy-maier** [comment]
Ok, I see. I agree this is one way to address this.

I was more thinking in this direction, though:
```
zhmc_channel_usage_ratio{channel="0.0D", partition="PART1", shared="true"} 0.5
```

**Comment by andy-maier** [comment]
Hi Christian.
PR #67 addresses your request, although differently than you asked for, but I think in a better way.

The metric definition file can now define that a particular metric (e.g. channel-usage) gets labels added from other metric values (of the same metric group), as follows:

```
metric_groups:
  . . .
  channel-usage:
    prefix: channel
    fetch: True
    labels:
      - name: cpc
        value: resource  # this is a keyword and translated to the name of the resource to which the metric belongs
      - name: channel_css_chpid
        value: channel-name  # format: 'CSS.CHPID'
metrics:
  . . .
  channel-usage:
    channel-usage:
      percent: True
      exporter_name: usage_ratio
      exporter_desc: Usage ratio of the channel
```

This will result in this output being published:

```
# HELP zhmc_channel_usage_ratio Usage ratio of the channel
# TYPE zhmc_channel_usage_ratio gauge
zhmc_channel_usage_ratio{channel_css_chpid="0.00",cpc="P0000S27"} 0.0
```

The sample metric definition file has been updated to do this by default.
The PR will be part of version 0.5.0.
