### ISSUE TITLE
Error: Invalid 'resource' item in resource metric group storagegroup-resource in metrics file: console.storagegroup

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-prometheus-exporter#379]
**Describe the bug**
zhmc exporter gets to the end of enabling auto-update for LPARs, and then Errors

> Sep 19 17:04:22 s390-kvm-metrics zhmc_prometheus_exporter[1192568]: Enabling auto-update for LPAR P0095FA8.L59
> Sep 19 17:04:24 s390-kvm-metrics zhmc_prometheus_exporter[1192568]: Retrieving resources from the HMC for resource metric group partition-resource
> Sep 19 17:04:24 s390-kvm-metrics zhmc_prometheus_exporter[1192568]: Retrieving resources from the HMC for resource metric group storagegroup-resource
> Sep 19 17:04:24 s390-kvm-metrics zhmc_prometheus_exporter[1192568]: Error: Invalid 'resource' item in resource metric group storagegroup-resource in metrics file: console.storagegroup

**Expected behavior**
exporter does not exit

**To Reproduce**
Unknown.. this is a z16 machine, and I'm  using the latest version v1.4.2 of the exporter.

**Environment information**
* Output of `zhmc_prometheus_exporter --version`: v1.4.2
* HMC version: 2.16.0

**Command output**
<-- Relevant parts of the command output. If possible, with '-vv'. -->

**Log file**
<-- If possible, attach a log file generated with '--log-comp all=debug --log exporter.log'. -->

**Comment by andy-maier** [comment]
Hi Vance. Sorry for the delay.
Can you please double check whether there is a trailing blank on the line "resource: console.storagegroup" in your metrics.yaml file? If not, can you please send your metrics file to me?

Around line 140:
```
  storagegroup-resource:
    type: resource
    resource: console.storagegroup
    prefix: storagegroup
    fetch: true
    labels:
      - name: cpc
        value: "uri2resource(resource_obj.properties['cpc-uri']).name"
      - name: storagegroup
        value: "resource_obj.name"
```
