### ISSUE TITLE
Add labels to channel-usage metrics for channel, partition, shared

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#52]
At the HMC level, the channel name, partition name and a boolean indicating whether the channel is shared are returned as string or boolean metrics. However, Prometheus only supports metrics with numeric values. Also, these attributes are not really metrics but rather represent additional information for the channel usage metrics. Prometheus can represent such resource context as labels on the metrics value.

The proposal is to generate channel-usage metric records that specify this context as labels, e.g.:

```
zhmc_channel_usage_ratio{channel="0.0D", partition="PART1", shared="true"} 0.5
```

The definition of these labels could be done in the metric definition file, consistent with the approach for issue #47.
For example:

```
metric_groups:
  channel-usage:
    prefix: channel
    fetch: True
    labels:
      - label: channel
        metric: channel-name
        desc: Name of the channel in the form 'CSS.CHPID'
      - label: shared
        metric: shared-channel
        desc: Boolean indicating whether the channel is shared among LPARs
      - label: partition
        metric: logical-partition-name
        desc: Name of the owning LPAR, 'shared', or empty string
```
