### ISSUE TITLE
Docs: Example config file has incorrect single "hmc"

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#703]
The example config file at https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/master/examples/config.yaml incorrectly allows for only a single HMC:

```
hmc:
  host: 9.10.11.12
  userid: userid
  password: password
  verify_cert: false
```

The schema file https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/master/zhmc_prometheus_exporter/schemas/config_schema.yaml#L13C1-L13C8 and the description of the config file structure both support a list of HMCs:

```
hmcs:
  - host: {hmc-ip-address}
    userid: {hmc-userid}
    password: {hmc-password}
    verify_cert: {hmc-verify-cert}
```

This issue is to fix the example config file to also show the list of hmcs.

In addition, it should be explained that at this point, only the first HMC in the list is used.
